server:
  port: 80
spring:
  cloud:
    consul:
      host: 192.168.239.132
      port: 8500
      discovery:
        instance-id: spring-consumer
        #service-name: consumer
  application:
    name: spring-consumer